# Starter pipeline
trigger:
- master

pool: samplePool

steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          javac HelloWorld.java
           
          
           java HelloWorld